version: '3.8'

services:
  postgres-server:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskmanagerdb
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  task-manager-server:
    build: .
    container_name: task_manager_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres-server
    links:
      - postgres-server
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

volumes:
  postgres_data:
